name: CI Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Next.js
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Hacer checkout del repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Configurar Node
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"

      # 3️⃣ Instalar dependencias
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Chequear tipos TypeScript
      - name: Typecheck
        run: npm run typecheck

      # 5️⃣ Build de Next.js
      - name: Build
        run: npm run build
