# .github/workflows/ci-test.yml
name: CI - Tests

# Se ejecuta en cada Pull Request hacia main
on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Run Vitest Tests
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      # 3️⃣ Instalar dependencias
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Ejecutar TypeScript typecheck (opcional)
      - name: TypeCheck
        run: npm run typecheck

      # 5️⃣ Ejecutar tests en modo CI
      - name: Run Vitest
        run: npm run test:ci

      # 6️⃣ (Opcional) Subir cobertura como artefacto
      # - name: Upload coverage
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: coverage-report
      #     path: coverage
