name: Docker Publish

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write   # necesario para publicar en GHCR

    steps:
      # 1️⃣ Checkout del repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Login a GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3️⃣ Construcción y push de la imagen
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/yamicaviglione/progra-entrega10:latest
            ghcr.io/yamicaviglione/progra-entrega10:${{ github.sha }}
